#!/bin/bash
OUT=TiddlyWiki5/plugins/anicolao/tw5-firestore-sync/firestoreadaptor.js
cat build/firestoreadaptor.js |
	sed -re 's/_firestoreadaptor//' -e '/^var Ea;$/d' > $OUT
cd TiddlyWiki5
node ./tiddlywiki.js editions/firestore --build index
cd -
mkdir -p dist/tw
cp TiddlyWiki5/editions/firestore/output/index.html dist/tw
